import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.svg', 'student_hub_app_icon.png', 'icons.svg'],
      manifest: {
        name: 'Smart Student Hub',
        short_name: 'Student Hub',
        description: 'Premium Student Portfolio & Achievement Tracking System',
        theme_color: '#2563eb',
        background_color: '#f9fafb',
        display: 'standalone',
        scope: '/',
        start_url: '/',
        icons: [
          {
            src: '/student_hub_app_icon.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: '/student_hub_app_icon.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: '/student_hub_app_icon.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any maskable',
          },
        ],
        shortcuts: [
          {
            name: 'My Portfolio',
            short_name: 'Portfolio',
            url: '/student/dashboard',
            icons: [{ src: '/student_hub_app_icon.png', sizes: '512x512' }],
          },
        ],
      },
      workbox: {
        // Cache all JS/CSS/HTML assets generated by Vite (including hashed filenames)
        globPatterns: ['**/*.{js,css,html,ico,png,svg,webp}'],
        // Never cache API calls to the backend
        navigateFallback: '/index.html',
        navigateFallbackDenylist: [/^\/api/],
        runtimeCaching: [
          {
            // Cache API responses with network-first strategy
            urlPattern: /^https:\/\/smart-student-hub-0ew4\.onrender\.com\/api\/.*/i,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'api-cache',
              expiration: {
                maxEntries: 50,
                maxAgeSeconds: 60 * 5, // 5 minutes
              },
              networkTimeoutSeconds: 10,
            },
          },
          {
            // Cache images with cache-first strategy
            urlPattern: /\.(?:png|jpg|jpeg|svg|gif|webp)$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'image-cache',
              expiration: {
                maxEntries: 100,
                maxAgeSeconds: 60 * 60 * 24 * 7, // 1 week
              },
            },
          },
        ],
      },
      devOptions: {
        enabled: false, // Disable SW in dev to avoid confusion
      },
    }),
  ],
})
